#!/usr/bin/env python

import sys
from catkin_lint.main import main

# Treat warnings as errors and output result as text with explanations.
# The number is 1 since 0 is the name of the program.
sys.argv[1:1] = ["-W2", "--strict", "--explain"]
print(sys.argv)
main()
