#!/usr/bin/env python

import sys
try:
    from roslint import pycodestyle
except ImportError:
    # Allows the target to work with an un-sourced workspace.
    import os.path
    sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "src"))
    from roslint import pycodestyle

pycodestyle.MAX_LINE_LENGTH = 120

pycodestyle._main()
